apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-workload-sa
  namespace: default
  annotations:
    # Remplacez par votre compte de service GSA (visible dans terraform output)
    iam.gke.io/gcp-service-account: "ai-demo-xxxx-gke-ai-sa@VOTRE_PROJECT_ID.iam.gserviceaccount.com"
